version: "3"
services:
  app:
    build: .
    container_name: app
    ports:
      - 8080:3000
    volumes:
      - ./:/home/app
    links: 
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - 27017:27017
    volumes: 
      - ./data:/data/db